package com.miaoshaproject.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.curent_value
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    private Integer curentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.stop
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    private Integer stop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.curent_value
     *
     * @return the value of sequence_info.curent_value
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    public Integer getCurentValue() {
        return curentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.curent_value
     *
     * @param curentValue the value for sequence_info.curent_value
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    public void setCurentValue(Integer curentValue) {
        this.curentValue = curentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.stop
     *
     * @return the value of sequence_info.stop
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    public Integer getStop() {
        return stop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.stop
     *
     * @param stop the value for sequence_info.stop
     *
     * @mbg.generated Mon Nov 25 14:23:26 CST 2019
     */
    public void setStop(Integer stop) {
        this.stop = stop;
    }
}